 dynamic:
  settings:
    dyn-set-test-dto: \r\ndyn-set-string: 'initString'\r\ndyn-set-integer: 111\r\ndyn-set-boolean: true\r\nfirst-test-dto:\r\n  second-test-dto:\r\n    str-field: 'initSecTestDtoString'\r\nfirst-test-dto-list:\r\n  - second-test-dto:\r\n      str-field: 'initSecTestDtoString'\r\n  - second-test-dto:\r\n      str-field: 'initSecTestDtoString1'\r\nmap:\r\n  key0:\r\n    second-test-dto:\r\n      str-field: 'initSecTestDtoString'\r\n  key1:\r\n    second-test-dto:\r\n      str-field: 'initSecTestDtoString1'

    simple:
      my-obj:
        my-string: 'from git'
        my-simple-obj:
          simple-field: 'field from git'
        my-string-list:
          - 'first elem from git'
          - 'second elem from git'
        my-simple-obj-list:
          - simple-field: '1 field from git'
          - simple-field: '2 field from git'
        my-string-string-map:
          first-key: '1 value field from git'
          second-key: '2 value field from git'
        my-string-obj-map:
          first-key:
            simple-field: '1 field from git'
          second-key:
            simple-field: '2 field from git'

    json: '{
  "dynSetString": "initString",
  "dynSetInteger": 333,
  "dynSetBoolean": true,
  "firstTestDto": {
    "secondTestDto": {
      "strField": "initSecTestDtoString"
    }
  },
  "firstTestDtoList": [
    {
      "secondTestDto": {
        "strField": "initSecTestDtoString"
      }
    },
    {
      "secondTestDto": {
        "strField": "initSecTestDtoString1"
      }
    }
  ],
  "map": {
    "key1": {
      "secondTestDto": {
        "strField": "initSecTestDtoString1"
      }
    },
    "key0": {
      "secondTestDto": {
        "strField": "initSecTestDtoString"
      }
    }
  }
}'
