dynamic:
  settings:
    dyn-set-test-dto:
      dyn-set-string: 'initString'
      dyn-set-integer: 111
      dyn-set-boolean: true
      first-test-dto:
        second-test-dto:
          str-field: 'initSecTestDtoString'
      firstTestDtoList:
        - second-test-dto:
            str-field: 'initSecTestDtoString'
    simple:
      my-obj:
        my-string: 'from git'
        my-simple-obj:
          simple-field: 'field from git'
        my-string-list:
          - 'first elem from git'
          - 'second elem from git'
        my-simple-obj-list:
          - simple-field: '1 field from git'
          - simple-field: '2 field from git'
        my-string-string-map:
          first-key: '1 value field from git'
          second-key: '2 value field from git'
        my-string-obj-map:
          first-key:
            simple-field: '1 field from git'
          second-key:
            simple-field: '2 field from git'
    json: '{
  "dynSetString": "updateString",
  "dynSetInteger": 222,
  "dynSetBoolean": false,
  "firstTestDto": {
    "secondTestDto": {
      "strField": "updateSecTestDtoString"
    }
  },
  "firstTestDtoList": [
    {
      "secondTestDto": {
        "strField": "updateSecTestDtoString"
      }
    },
    {
      "secondTestDto": {
        "strField": "updateSecTestDtoString1"
      }
    },
    {
      "secondTestDto": {
        "strField": "updateSecTestDtoString2"
      }
    }
  ],
  "map": {
    "key2": {
      "secondTestDto": {
        "strField": "updateSecTestDtoString2"
      }
    },
    "key1": {
      "secondTestDto": {
        "strField": "updateSecTestDtoString1"
      }
    },
    "key0": {
      "secondTestDto": {
        "strField": "updateSecTestDtoString"
      }
    }
  }
}'
