dynamic:
  settings:
    json: '{
  "dynSetString": "initString",
  "dynSetInteger": 111,
  "dynSetBoolean": true,
  "firstTestDto": {
    "secondTestDto": {
      "strField": "initSecTestDtoString"
    }
  },
  "firstTestDtoList": [
    {
      "secondTestDto": {
        "strField": "initSecTestDtoString"
      }
    },
    {
      "secondTestDto": {
        "strField": "initSecTestDtoString1"
      }
    }
  ],
  "map": {
    "key1": {
      "secondTestDto": {
        "strField": "initSecTestDtoString1"
      }
    },
    "key0": {
      "secondTestDto": {
        "strField": "initSecTestDtoString"
      }
    }
  }
}'
