dynamic:
  settings:
    json: '{
  "dynSetString": "updateString",
  "dynSetInteger": 222,
  "dynSetLong": 222,
  "dynSetBoolean": false,
  "firstTestDto": {
    "secondTestDto": {
      "strField": "updateSecTestDtoString"
    }
  },
  "firstTestDtoList": [
    {
      "secondTestDto": {
        "strField": "updateSecTestDtoString"
      }
    },
    {
      "secondTestDto": {
        "strField": "updateSecTestDtoString1"
      }
    },
    {
      "secondTestDto": {
        "strField": "updateSecTestDtoString2"
      }
    }
  ],
  "map": {
    "key2": {
      "secondTestDto": {
        "strField": "updateSecTestDtoString2"
      }
    },
    "key1": {
      "secondTestDto": {
        "strField": "updateSecTestDtoString1"
      }
    },
    "key0": {
      "secondTestDto": {
        "strField": "updateSecTestDtoString"
      }
    }
  }
}'
