my:
  name: Yan
  surname: Karpovich
  json: '{
  "name": "Ilya",
  "surname": "Popenuk",
  "list": [
    "firstElem",
    "secondElem"
  ],
  "mapClass": {
    "firstKey": "firstValue",
    "secondKey": "secondValue",
    "thirdKey": "thirdValue"
  },
  "map": {
    "firstKey": "firstValue",
    "secondKey": "secondValue",
    "thirdKey": "thirdValue"
  }
}'
