 dynamic:
  settings:
    dyn-set-test-dto:
      dyn-set-string: 'updateString'
      dyn-set-integer: 222
      dyn-set-boolean: false
      first-test-dto:
        second-test-dto:
          str-field: 'updateSecTestDtoString'
      first-test-dto-list:
        - second-test-dto:
            str-field: 'updateSecTestDtoString'
        - second-test-dto:
            str-field: 'updateSecTestDtoString1'
        - second-test-dto:
            str-field: 'updateSecTestDtoString2'
      map:
        key0:
          second-test-dto:
            str-field: 'updateSecTestDtoString'
        key1:
          second-test-dto:
            str-field: 'updateSecTestDtoString1'
        key2:
          second-test-dto:
            str-field: 'updateSecTestDtoString1'

    simple:
      my-obj:
        my-string: 'from git'
        my-simple-obj:
          simple-field: 'field from git'
        my-string-list:
          - 'first elem from git'
          - 'second elem from git'
        my-simple-obj-list:
          - simple-field: '1 field from git'
          - simple-field: '2 field from git'
        my-string-string-map:
          first-key: '1 value field from git'
          second-key: '2 value field from git'
        my-string-obj-map:
          first-key:
            simple-field: '1 field from git'
          second-key:
            simple-field: '2 field from git'

