 dynamic:
  settings:
    simple:
      my-string: 'from git'
      my-simple-obj:
        simple-field: 'field from git'
      my-string-list:
        - 'first elem from yml'
        - 'second elem from yml'
    json: '{
  "dynSetString": "updateString",
  "dynSetInteger": 222,
  "dynSetBoolean": false,
  "firstTestDto": {
    "secondTestDto": {
      "strField": "updateSecTestDtoString"
    }
  },
  "firstTestDtoList": [
    {
      "secondTestDto": {
        "strField": "updateSecTestDtoString"
      }
    },
    {
      "secondTestDto": {
        "strField": "updateSecTestDtoString1"
      }
    },
    {
      "secondTestDto": {
        "strField": "updateSecTestDtoString2"
      }
    }
  ],
  "map": {
    "key2": {
      "secondTestDto": {
        "strField": "updateSecTestDtoString2"
      }
    },
    "key1": {
      "secondTestDto": {
        "strField": "updateSecTestDtoString1"
      }
    },
    "key0": {
      "secondTestDto": {
        "strField": "updateSecTestDtoString"
      }
    }
  }
}'
